#!/bin/bash

curl -w @- -o /dev/null -s "$@" <<'EOF'
 %{scheme}/%{http_version} %{method} %{http_code}\n
 content-type:  %{content_type}\n
 content-length:  %{size_download} bytes\n
                    ----------\n
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n

                    ----------\n
         time_total:  %{time_total}\n
EOF
